version: '3.9'

services:
  frontend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: 'lwaero/frontend-store'
    container_name: frontend
    env_file: .env.development
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - ./app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
