version: '3.9'

services:
  frontend:
    image: 'lwaero/frontend'
    container_name: frontend
    env_file: .env.development
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - ./app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    