version: '3.9'

services:
  frontend:
    image: 'lwaero/frontend-store'
    container_name: frontend
    env_file: .env.production
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    command: 'yarn start'